FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ARG NEXT_PUBLIC_FASTAPI_URL=http://127.0.0.1:8000
ENV NEXT_PUBLIC_FASTAPI_URL=$NEXT_PUBLIC_FASTAPI_URL

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]